#/bin/bash

TODAY=$(date +%Y%m%d)

REPORT_DIR=reports
mkdir $REPORT_DIR

MYSQL_TABLE=evr_indicators_v8
MYSQL_USER="evr"
MYSQL_PW="evr"
MYSQL_DB="evr_monitoring"


mysql -u $MYSQL_USER -p$MYSQL_PW $MYSQL_DB >$REPORT_DIR/all-$TODAY.csv <<EOF
select
e.name as site,
e.mesh_evr_cluster,
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 1 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 0 day), "%Y%m%d")) as '1_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 2 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 1 day), "%Y%m%d")) as '2_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 3 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 2 day), "%Y%m%d")) as '3_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 4 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 3 day), "%Y%m%d")) as '4_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 5 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 4 day), "%Y%m%d")) as '5_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 6 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 5 day), "%Y%m%d")) as '6_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 7 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 6 day), "%Y%m%d")) as '7_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 8 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 7 day), "%Y%m%d")) as '8_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 9 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 8 day), "%Y%m%d")) as '9_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 10 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 9 day), "%Y%m%d")) as '10_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 11 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 10 day), "%Y%m%d")) as '11_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 12 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 11 day), "%Y%m%d")) as '12_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 13 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 12 day), "%Y%m%d")) as '13_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count), "|", COALESCE(max(e2.mt_start_count)-min(e2.mt_start_count),-1), "|", (100/24)*sum(if((e2.http_speed >= 10 or e2.http_speed like '%MB%') and not (e2.http_speed like '%http%' or e2.http_speed like '%failed%' or e2.http_speed = ' '), 1, 0)), "||") from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 14 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 13 day), "%Y%m%d")) as '14_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin|mt_start|http_ok||'
from $MYSQL_TABLE e
where e.timestamp_corrected > date_format(date_sub(date(now()), interval 15 day), "%Y%m%d")
group by e.name, e.mesh_evr_cluster;
EOF

sed 's/NULL/|||||||||||/g' $REPORT_DIR/all-$TODAY.csv | tr '|' '\t' > $REPORT_DIR/all-$TODAY-2.csv
cat $REPORT_DIR/all-$TODAY-2.csv| tr '.' ',' > $REPORT_DIR/all-$TODAY-3.csv

cp $REPORT_DIR/all-$TODAY-3.csv /var/www/html/recent-evr-monitor.csv
exit 0


# 2 more weeks instead of just the 2 last weeks
echo <<EOF
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 15 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 14 day), "%Y%m%d")) as '15_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 16 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 15 day), "%Y%m%d")) as '16_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 17 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 16 day), "%Y%m%d")) as '17_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 18 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 17 day), "%Y%m%d")) as '18_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 19 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 18 day), "%Y%m%d")) as '19_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 20 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 19 day), "%Y%m%d")) as '20_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 21 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 20 day), "%Y%m%d")) as '21_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 22 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 21 day), "%Y%m%d")) as '22_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 23 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 22 day), "%Y%m%d")) as '23_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 24 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 23 day), "%Y%m%d")) as '24_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 25 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 24 day), "%Y%m%d")) as '25_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 26 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 25 day), "%Y%m%d")) as '26_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 27 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 26 day), "%Y%m%d")) as '27_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 28 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 27 day), "%Y%m%d")) as '28_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 29 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 28 day), "%Y%m%d")) as '29_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin',
(select CONCAT((100/24)*sum(if(ping_exit_code='0', 1, 0)), "|", ((100/24)*count(*)), "|", max(e2.crash_count)-min(e2.crash_count) , "|", max(e2.start_count)-min(e2.start_count), "|" , max(mt_voltage), "|", min(mt_voltage), "|", max(mesh_neigbor_count) ,"|", min(mesh_neigbor_count)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.timestamp_corrected > date_format(date_sub(date(now()), interval 30 day), "%Y%m%d") and e2.timestamp_corrected < date_format(date_sub(date(now()), interval 29 day), "%Y%m%d")) as '30_ping|uptime|crash|start|Vmax|Vmin|PeerMax|PeerMin'

EOF

# below is all combined in above query, no longer needed

# j2 daily active with connectivity once per day for last 30 days
mysql -u $MYSQL_USER -p$MYSQL_PW $MYSQL_DB >$REPORT_DIR/daily_active-$TODAY.csv <<EOF
select
e.name,
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 1 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 0 day), "%Y%m%d")), 1, 0) as '1ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 2 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 1 day), "%Y%m%d")), 1, 0) as '2ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 3 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 2 day), "%Y%m%d")), 1, 0) as '3ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 4 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 3 day), "%Y%m%d")), 1, 0) as '4ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 5 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 4 day), "%Y%m%d")), 1, 0) as '5ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 6 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 5 day), "%Y%m%d")), 1, 0) as '6ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 7 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 6 day), "%Y%m%d")), 1, 0) as '7ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 8 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 7 day), "%Y%m%d")), 1, 0) as '8ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 9 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 8 day), "%Y%m%d")), 1, 0) as '9ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 10 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 9 day), "%Y%m%d")), 1, 0) as '10ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 11 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 10 day), "%Y%m%d")), 1, 0) as '11ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 12 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 11 day), "%Y%m%d")), 1, 0) as '12ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 13 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 12 day), "%Y%m%d")), 1, 0) as '13ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 14 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 13 day), "%Y%m%d")), 1, 0) as '14ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 15 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 14 day), "%Y%m%d")), 1, 0) as '15ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 16 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 15 day), "%Y%m%d")), 1, 0) as '16ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 17 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 16 day), "%Y%m%d")), 1, 0) as '17ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 18 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 17 day), "%Y%m%d")), 1, 0) as '18ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 19 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 18 day), "%Y%m%d")), 1, 0) as '19ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 20 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 19 day), "%Y%m%d")), 1, 0) as '20ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 21 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 20 day), "%Y%m%d")), 1, 0) as '21ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 22 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 21 day), "%Y%m%d")), 1, 0) as '22ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 23 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 22 day), "%Y%m%d")), 1, 0) as '23ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 24 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 23 day), "%Y%m%d")), 1, 0) as '24ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 25 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 24 day), "%Y%m%d")), 1, 0) as '25ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 26 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 25 day), "%Y%m%d")), 1, 0) as '26ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 27 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 26 day), "%Y%m%d")), 1, 0) as '27ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 28 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 27 day), "%Y%m%d")), 1, 0) as '28ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 29 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 28 day), "%Y%m%d")), 1, 0) as '29ago',
if (exists(select * from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 30 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 29 day), "%Y%m%d")), 1, 0) as '30ago'
from $MYSQL_TABLE e
group by e.name;
EOF

# j2 daily start count
mysql -u $MYSQL_USER -p$MYSQL_PW $MYSQL_DB >$REPORT_DIR/daily_start-$TODAY.csv <<EOF
select
e.name,
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 1 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 0 day), "%Y%m%d")) as '1ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 2 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 1 day), "%Y%m%d")) as '2ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 3 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 2 day), "%Y%m%d")) as '3ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 4 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 3 day), "%Y%m%d")) as '4ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 5 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 4 day), "%Y%m%d")) as '5ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 6 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 5 day), "%Y%m%d")) as '6ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 7 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 6 day), "%Y%m%d")) as '7ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 8 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 7 day), "%Y%m%d")) as '8ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 9 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 8 day), "%Y%m%d")) as '9ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 10 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 9 day), "%Y%m%d")) as '10ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 11 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 10 day), "%Y%m%d")) as '11ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 12 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 11 day), "%Y%m%d")) as '12ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 13 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 12 day), "%Y%m%d")) as '13ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 14 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 13 day), "%Y%m%d")) as '14ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 15 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 14 day), "%Y%m%d")) as '15ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 16 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 15 day), "%Y%m%d")) as '16ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 17 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 16 day), "%Y%m%d")) as '17ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 18 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 17 day), "%Y%m%d")) as '18ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 19 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 18 day), "%Y%m%d")) as '19ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 20 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 19 day), "%Y%m%d")) as '20ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 21 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 20 day), "%Y%m%d")) as '21ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 22 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 21 day), "%Y%m%d")) as '22ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 23 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 22 day), "%Y%m%d")) as '23ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 24 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 23 day), "%Y%m%d")) as '24ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 25 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 24 day), "%Y%m%d")) as '25ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 26 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 25 day), "%Y%m%d")) as '26ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 27 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 26 day), "%Y%m%d")) as '27ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 28 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 27 day), "%Y%m%d")) as '28ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 29 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 28 day), "%Y%m%d")) as '29ago',
(select max(e2.start_count)-min(e2.start_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 30 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 29 day), "%Y%m%d")) as '30ago'
from $MYSQL_TABLE e
group by e.name;
EOF

# j2 daily crash count
mysql -u $MYSQL_USER -p$MYSQL_PW $MYSQL_DB >$REPORT_DIR/daily_crash-$TODAY.csv <<EOF
select
e.name,
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 1 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 0 day), "%Y%m%d")) as '1ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 2 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 1 day), "%Y%m%d")) as '2ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 3 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 2 day), "%Y%m%d")) as '3ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 4 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 3 day), "%Y%m%d")) as '4ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 5 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 4 day), "%Y%m%d")) as '5ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 6 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 5 day), "%Y%m%d")) as '6ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 7 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 6 day), "%Y%m%d")) as '7ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 8 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 7 day), "%Y%m%d")) as '8ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 9 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 8 day), "%Y%m%d")) as '9ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 10 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 9 day), "%Y%m%d")) as '10ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 11 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 10 day), "%Y%m%d")) as '11ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 12 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 11 day), "%Y%m%d")) as '12ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 13 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 12 day), "%Y%m%d")) as '13ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 14 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 13 day), "%Y%m%d")) as '14ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 15 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 14 day), "%Y%m%d")) as '15ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 16 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 15 day), "%Y%m%d")) as '16ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 17 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 16 day), "%Y%m%d")) as '17ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 18 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 17 day), "%Y%m%d")) as '18ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 19 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 18 day), "%Y%m%d")) as '19ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 20 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 19 day), "%Y%m%d")) as '20ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 21 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 20 day), "%Y%m%d")) as '21ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 22 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 21 day), "%Y%m%d")) as '22ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 23 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 22 day), "%Y%m%d")) as '23ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 24 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 23 day), "%Y%m%d")) as '24ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 25 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 24 day), "%Y%m%d")) as '25ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 26 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 25 day), "%Y%m%d")) as '26ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 27 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 26 day), "%Y%m%d")) as '27ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 28 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 27 day), "%Y%m%d")) as '28ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 29 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 28 day), "%Y%m%d")) as '29ago',
(select max(e2.crash_count)-min(e2.crash_count) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 30 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 29 day), "%Y%m%d")) as '30ago'
from $MYSQL_TABLE e
group by e.name;
EOF

mysql -u $MYSQL_USER -p$MYSQL_PW $MYSQL_DB >$REPORT_DIR/daily_j2_uptime-$TODAY.csv <<EOF
select
e.name,
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 1 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 0 day), "%Y%m%d")) as '1ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 2 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 1 day), "%Y%m%d")) as '2ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 3 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 2 day), "%Y%m%d")) as '3ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 4 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 3 day), "%Y%m%d")) as '4ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 5 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 4 day), "%Y%m%d")) as '5ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 6 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 5 day), "%Y%m%d")) as '6ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 7 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 6 day), "%Y%m%d")) as '7ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 8 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 7 day), "%Y%m%d")) as '8ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 9 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 8 day), "%Y%m%d")) as '9ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 10 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 9 day), "%Y%m%d")) as '10ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 11 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 10 day), "%Y%m%d")) as '11ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 12 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 11 day), "%Y%m%d")) as '12ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 13 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 12 day), "%Y%m%d")) as '13ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 14 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 13 day), "%Y%m%d")) as '14ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 15 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 14 day), "%Y%m%d")) as '15ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 16 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 15 day), "%Y%m%d")) as '16ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 17 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 16 day), "%Y%m%d")) as '17ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 18 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 17 day), "%Y%m%d")) as '18ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 19 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 18 day), "%Y%m%d")) as '19ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 20 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 19 day), "%Y%m%d")) as '20ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 21 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 20 day), "%Y%m%d")) as '21ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 22 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 21 day), "%Y%m%d")) as '22ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 23 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 22 day), "%Y%m%d")) as '23ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 24 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 23 day), "%Y%m%d")) as '24ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 25 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 24 day), "%Y%m%d")) as '25ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 26 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 25 day), "%Y%m%d")) as '26ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 27 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 26 day), "%Y%m%d")) as '27ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 28 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 27 day), "%Y%m%d")) as '28ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 29 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 28 day), "%Y%m%d")) as '29ago',
(select ((100/24)*count(*)) from $MYSQL_TABLE e2 where e2.name = e.name and e2.server_time > date_format(date_sub(date(now()), interval 30 day), "%Y%m%d") and e2.server_time < date_format(date_sub(date(now()), interval 29 day), "%Y%m%d")) as '30ago'
from $MYSQL_TABLE e
group by e.name;
EOF

